apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: banking-network-policy
spec:
  podSelector:
    matchLabels:
      app: banking-app
  policyTypes:
  - Ingress
  ingress:
  - from:
    - ipBlock:
        cidr: 0.0.0.0/0 # Allows external traffic to frontend
    ports:
    - protocol: TCP
      port: 80
